config/routes.rb
Rails.application.routes.draw do
  
  root  'pages#home'

  devise_for :users, 
    :path => '', :path_names => {:sign_in    =>  'login', :sign_out   =>  'logout', :sign_up    =>   'signup'}

  get 'users/new'
  get 'users/show'
  get 'help'    =>  'pages#help'
  get 'about'   =>  'pages#about'
  get 'contact' =>  'pages#contact'

  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'following' => 'users#show', as: :following

  resources :microposts,      only: [:create, :destroy]
  resources :relationships,   only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  
  belongs_to :user
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates	:content, presence: true, length: { maximum: 140 }
  validate 	:picture_size

  private

  def picture_size
  	if picture.size > 2.megabytes
  		errors.add(:picture, "should be less than 2MB")
  	end
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"	
	belongs_to :followed, class_name: "User"
	validates	:follower_id, presence: true	
	validates	:followed_id, presence: true	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

has_many :microposts, dependent: :destroy
has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :following, through: :active_relationships, source: :followed
has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :followers, through: :passive_relationships, source: :follower
has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def fullname
    fullname = "#{f_name} #{l_name}"
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                      WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                    OR user_id = :user_id", user_id: id)
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_up_path_for(resource)
    @user
  end

  def after_sign_in_path_for(resource)
	  root_url
	end

protected

	def configure_permitted_parameters
	      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :f_name, :l_name)}
	      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :current_password, :password , :password_confirmation, :f_name, :l_name, :avatar)}
	end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  before_filter :authenticate_user!,  only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)

    if @micropost.save 
      flash[:success] = 'Micropost was successfully created.'
      redirect_to root_url
    else
      @feed_items = []
      render 'pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost delete successfully"
    redirect_to :back
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :user_id, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		if user_signed_in?
	  	@micropost = current_user.microposts.build
	  	@feed_items = current_user.feed.paginate(page: params[:page]).order(created_at: :desc)
		end
	end

	def help
		@title = "Help"
	end

	def about
		@title = "About"
	end

	def contact
		@title = "Contact"
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_filter :authenticate_user!

	def create
		user = User.find(params[:followed_id])
		current_user.follow(user)
		redirect_to user
	end

	def destroy
		relationship = Relationship.find(params[:id])
		relationship.destroy
		redirect_to :back
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate_user!,	only: [:index, :following, :followers]
  
	def index
		@users = User.paginate(page: params[:page])
	end	

  def new
  end

  def show
  	@user = User.find(params[:id])
  	@microposts = @user.microposts.paginate(page: params[:page]).order(created_at: :desc)
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])    
    render 'show_follow'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "info"
        "alert-warning"   # Yellow
      when "notice"
        # "alert-info"      # Blue
        "alert-success"
      else
        flash_type.to_s
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def avatar(user)
		image_tag(user.avatar.url(:thumb), size: "50x50", alt: user.fullname, class: "gravatar")
	end

	def avatar2(user)
		image_tag(user.avatar.url(:thumb), size: "30x30", alt: user.fullname, class: "gravatar")
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> Tweettoo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<%= render 'shared/header' %>
	<div class="container">
		<% flash.each do |type, message| %>
		  <div class="alert <%= bootstrap_class_for(type) %> fade in">
		    <button class="close" data-dismiss="alert">×</button>
		    <%= message %>
		  </div>
		<% end %>
		<%= yield %>
		<%= render 'shared/footer' %>
	</div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
	<%= link_to avatar(micropost.user), micropost.user %>
	<span class="user"><%= link_to micropost.user.fullname, micropost.user %></span>
	<span class="content">
		<%= micropost.content %>
		<%= image_tag micropost.picture.url if micropost.picture? %>
	</span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(micropost.created_at) %> ago.
		<% if current_user && micropost.user == current_user %>
			<%= link_to "delete", micropost, method: :delete, data: { confirm: "Are you sure..?"} %>
		<% end %>
	</span>
</li>

app/views/pages/about.html.erb
<% provide(:title, "About |") %>
<h1>About Page</h1>

app/views/pages/contact.html.erb
<% provide(:title, "Contact |") %>
<h1>Contact Page</h1>

app/views/pages/help.html.erb
<% provide(:title, "Help |") %>
<h1>Help Page</h1>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<div class="row">
		<aside class="col-md-4">
			<section class="user_info">
				<%= render 'shared/user_info' %>
			</section>
			<section class="stats">
				<%= render 'shared/stats' %>
			</section>
			<section>
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
		<div class="col-md-8">
			<h3>Micropost Feed</h3>
			<%= render 'shared/feed' %>
		</div>	
	</div>
<% else %>
	<div class="center jumbotron">
		<h1>Welcome to Tweettoo</h1>
		<h2>
			This is twitter base application for our final project submittion.
		</h2>
		<p>
			For final project subittion we made the twitter base application for the tyring to making such like application in future and learning for <%= link_to "Ruby on Rails", "http://www.rubyonrails.org" %>. In this we are 4 students are subitting this project. <br> 1. Ghulam Murtaza 2. Kalsoom Akhtar 3. Safiullah 4. Manzoor Ahmed <br> and we follow the book <%= link_to "Ruby on Rails Tutorial", "http://www.railstutorial.org" %> by 
			<%= link_to "Michael Hartl", "http://www.michaelhartl.com" %>.
		</p>
		<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
	</div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>		
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
	<small>
		The <%= link_to "Tweettoo", "/" %> application by 
				<%= link_to "Ghulam Murtaza", "http://www.facebook.com/GhulaMurtazaRind" %>, 
				<%= link_to "Kalsoom Akhtar", "http://www.facebook.com/kalsoom.iqbal.50" %>, 
				<%= link_to "Safiullah", 			"http://www.facebook.com/safiullah.jan.129" %>, 
				<%= link_to "Manzoor Ahmed", 	"http://www.facebook.com/manzoor.ahmed.7161" %>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", 		about_path %></li>
			<li><%= link_to "Contact", 	contact_path %></li>
			<li><%= link_to "News", 		"http://news.railstutorial.org/" %></li>
		</ul>
	</nav>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "tweettoo", "/", id: "logo" %>
		<nav>
			<ul class="nav navbar-nav pull-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Users", users_path %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">	
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Setting", edit_user_registration_path %></li>
							<li class="divider"></li>
							<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
						</ul>
					</li>
				<% else %>
				<li><%= link_to "Login", new_user_session_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new micropost...", class: "form-control" %>
	</div>
	<%= f.submit "Post", class: "btn btn-primary" %>
	<span class="picture">
		<%= f.file_field :picture %>
	</span>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.following.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to avatar(current_user), current_user %>
<h1><%= current_user.fullname %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
	<div><%= hidden_field_tag :followed_id, @user.id %></div>
	<%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user && (@user) != current_user %>
	<div class="follow_form">
		<% if current_user.following?(@user) %>
			<%= render 'unfollow' %>
		<% else %>
			<%= render 'follow' %>
		<% end %>
	</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }) do |f| %>
	<%= f.submit "Unfollow", class: "btn btn-default" %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |user| %>
	<% if user.fullname !=current_user.fullname %>
		<li>
			<%= link_to avatar(user), user %>
			<%= link_to user.fullname, user %>
		</li>
		<% end %>
<% end %>	
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<% provide(:title, "#{@user.fullname} |" ) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user-info">
			<h1>
				<%= avatar(@user) %>
				<%= @user.fullname %>
			</h1>			
		</section>
			<section class="stats">
				<%= render 'shared/stats' %>
			</section>
	</aside>
	<div class="col-md-8">
	<%= render 'follow_form' if user_signed_in? %>
	<% if @user.microposts.any? %>
		<h3>Microposts (<%= @user.microposts.count %>)</h3>
			<ol class="microposts">
				<%= render @microposts %>
			</ol>
			<%= will_paginate @microposts %>
		<% end %>
	</div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
	<aside class="col-md-4">
		<section class="user_inf">
			<%= avatar(@user) %>
			<h1><%= @user.fullname %></h1>
			<span><%= link_to "view my profile", @user %></span>
			<span><b>Microposts:</b> <%= @user.microposts.count %></span>
		</section>
		<section class="stats">
			<%= render 'shared/stats' %>
			<% if @users.any? %>
				<div class="user_avatars">
					<% @users.each do |user| %>
						<%= link_to avatar2(user), user %>
					<% end %>
				</div>	
			<% end %>
		</section>
	</aside>
	<div class="col-md-8">
	<h3><%= @title %></h3>
		<% if @users.any? %>
			<ul class="users follow">
				<% @users.each do |user| %>
					<li>
						<%= link_to avatar(user), user %>
						<%= link_to user.fullname, user %>
					</li>
			<% end %>	
			</ul>
			<%= will_paginate %>
		<% end %>
	</div>
</div>